version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - node --version
artifacts:
  files:
    - index.html
    - css/*
    - font-awesome/*
    - fonts/*
    - img/*
    - js/*
